# Lectura del parquet

In [184]:
# Leemos el archivo parquet 

import pandas as pd
dataset = pd.read_parquet('/home/jefferssonds/Documentos/datathon/data/casos_piura_limpio.parquet')
data = dataset.copy()

# Identificamos qué tipo de fechas tenemos

In [185]:
print('Rango de fecha de ingreso del registro al sistema',data['FECHA_ING'].min(), '-',data['FECHA_ING'].max())

print('-------------------------FECHAS DE EXTRACCIÓN------------------------------------')
print('Una sola fecha de recogió la muestra de la información',data['FECHA_MUESTRA'].max())
print('Una sola fecha de corte de la recolección de información',data['FECHA_CORTE'].max())

Rango de fecha de ingreso del registro al sistema 2020-01-04 00:00:00 - 2024-06-30 00:00:00
-------------------------FECHAS DE EXTRACCIÓN------------------------------------
Una sola fecha de recogió la muestra de la información 2024-06-30 00:00:00
Una sola fecha de corte de la recolección de información 2024-07-01 00:00:00

In [186]:
data.groupby('ANO')[['DAA_C1', 'DAA_C1_4', 'DAA_C5']].agg(['sum', 'mean', 'max'])

     DAA_C1                DAA_C1_4               DAA_C5
        sum      mean  max      sum      mean max    sum      mean  max
ANO
2020   4775  0.635904   80     9926  1.321880  66  20031  2.667599  201
2021   6321  0.666842   86    13064  1.378204  47  24587  2.593839  143
2022   7781  0.703272   93    16541  1.495029  72  32622  2.948482  239
2023   9902  0.784876  148    20631  1.635304  93  54165  4.293358  308
2024   5430  0.808397   92    11314  1.684383  42  15423  2.296114  183

In [187]:
data.loc[data['DAA_C5'] == 0, 'DAA_C5'] = (
    data.loc[data['DAA_C5'] == 0, 'DAA_C1'] + data.loc[data['DAA_C5'] == 0, 'DAA_C1_4']
)

In [188]:
import datetime

data['FECHA_SEMANA'] = data.apply(
    lambda row: pd.to_datetime(datetime.date.fromisocalendar(int(row['ANO']), int(row['SEMANA']), 1)),
    axis=1
)

In [197]:
data.rename(columns={'FECHA_SEMANA': 'FECHA_SINTOMAS'}, inplace=True)

In [198]:
data

,FECHA_CORTE,FECHA_MUESTRA,PROVINCIA,DISTRITO,UBIGEO,ANO,SEMANA,SUB_REG_NT,E_SALUD,DAA_C1,DAA_C1_4,DAA_C5,FECHA_ING,FECHA_SINTOMAS
0,2024-07-01,2024-06-30,SULLANA,SULLANA,200601,2024,26,31,200601A301,0,2,2,2024-06-30,2024-06-24
1,2024-07-01,2024-06-30,TALARA,LOS ORGANOS,200701,2024,26,31,200701D201,0,0,0,2024-06-30,2024-06-24
2,2024-07-01,2024-06-30,TALARA,LOS ORGANOS,200706,2024,26,31,200706A201,1,0,1,2024-06-30,2024-06-24
3,2024-07-01,2024-06-30,PIURA,LA ARENA,200109,2024,26,32,200109A307,0,2,2,2024-06-30,2024-06-24
4,2024-07-01,2024-06-30,PIURA,LA UNION,200110,2024,26,32,200110A304,0,0,0,2024-06-30,2024-06-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47380,2024-07-01,2024-06-30,HUANCABAMBA,HUANCABAMBA,200306,2020,1,48,200306A303,1,0,3,2020-01-05,2019-12-30
47381,2024-07-01,2024-06-30,HUANCABAMBA,HUANCABAMBA,200306,2020,1,48,200306A305,0,1,1,2020-01-05,2019-12-30
47382,2024-07-01,2024-06-30,HUANCABAMBA,HUANCABAMBA,200306,2020,1,48,200306A308,0,1,1,2020-01-05,2019-12-30
47383,2024-07-01,2024-06-30,MORROPON,MORROPON,200408,2020,1,48,200408A303,0,1,1,2020-01-05,2019-12-30
47384,2024-07-01,2024-06-30,MORROPON,MORROPON,200401,2020,1,48,200401C301,3,4,10,2020-01-04,2019-12-30